#!/usr/bin/env bash
# Pi-Factory First Run — deploy on a fresh Raspberry Pi 4
#
# What this does:
#   1. Installs system dependencies (python3, npm, git)
#   2. Creates /opt/pifactory with venv and pip install
#   3. Installs FUXA HMI via npm
#   4. Prompts for NIM API key and Telegram token
#   5. Saves config to /etc/pifactory/config.env
#   6. Installs systemd services (tag server + telegram bot)
#   7. Enables services for auto-start on boot
#
# Usage:
#   sudo ./pifactory/setup/firstrun.sh

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[Pi-Factory]${NC} $*"; }
warn() { echo -e "${YELLOW}[Pi-Factory]${NC} $*"; }
err()  { echo -e "${RED}[Pi-Factory]${NC} $*"; exit 1; }

# Must be root
[[ $EUID -eq 0 ]] || err "Run with sudo: sudo $0"

INSTALL_DIR="/opt/pifactory"
CONFIG_DIR="/etc/pifactory"
REPO_DIR="$(cd "$(dirname "$0")/../.." && pwd)"

log "Pi-Factory First Run Setup"
log "Repo: $REPO_DIR"
echo

# ─── 1. System deps ──────────────────────────────────────────────────────────
log "Installing system dependencies..."
apt-get update -qq
apt-get install -y -qq python3 python3-venv python3-pip git curl nodejs npm

# ─── 2. Application install ──────────────────────────────────────────────────
log "Setting up $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR"
cp -r "$REPO_DIR"/* "$INSTALL_DIR/"

log "Creating Python virtual environment..."
python3 -m venv "$INSTALL_DIR/.venv"
"$INSTALL_DIR/.venv/bin/pip" install --upgrade pip -q
"$INSTALL_DIR/.venv/bin/pip" install -r "$INSTALL_DIR/requirements.txt" -q
log "Python dependencies installed."

# ─── 3. FUXA HMI ─────────────────────────────────────────────────────────────
log "Installing FUXA HMI..."
if command -v fuxa &> /dev/null; then
    warn "FUXA already installed, skipping."
else
    npm install -g @nicedash/fuxa-server 2>/dev/null || {
        warn "FUXA npm install failed — you can install it later:"
        warn "  npm install -g @nicedash/fuxa-server"
    }
fi

# ─── 4. Configuration ────────────────────────────────────────────────────────
mkdir -p "$CONFIG_DIR"

if [[ -f "$CONFIG_DIR/config.env" ]]; then
    warn "Config already exists at $CONFIG_DIR/config.env — keeping existing."
else
    log "Configuration setup..."
    echo

    read -rp "NVIDIA Cosmos NIM API key (or press Enter to skip): " NIM_KEY
    read -rp "Telegram bot token (or press Enter to skip): " TG_TOKEN
    read -rp "Telegram chat ID (or press Enter to skip): " TG_CHAT

    cat > "$CONFIG_DIR/config.env" <<EOF
# Pi-Factory Configuration — generated by firstrun.sh
NVIDIA_COSMOS_API_KEY=${NIM_KEY:-}
TELEGRAM_BOT_TOKEN=${TG_TOKEN:-}
TELEGRAM_CHAT_ID=${TG_CHAT:-}
ALLOWED_CHAT_IDS=${TG_CHAT:-}
ANYBUS_HARDWARE=false
VIDEO_SOURCE=
PORT=8080
EOF

    chmod 600 "$CONFIG_DIR/config.env"
    log "Config saved to $CONFIG_DIR/config.env"
fi

# ─── 5. systemd services ─────────────────────────────────────────────────────
log "Installing systemd services..."

cp "$REPO_DIR/pifactory/setup/pifactory.service" /etc/systemd/system/
cp "$REPO_DIR/pifactory/setup/telegram.service" /etc/systemd/system/

systemctl daemon-reload
systemctl enable pifactory.service
systemctl enable telegram.service

log "Services enabled. Starting..."
systemctl start pifactory.service || warn "Tag server start failed — check: journalctl -u pifactory"
systemctl start telegram.service  || warn "Telegram bot start failed — check: journalctl -u telegram"

# ─── 6. Done ─────────────────────────────────────────────────────────────────
echo
log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log "  Pi-Factory is installed!"
log ""
log "  Tag API:   http://$(hostname -I | awk '{print $1}'):8080/api/tags"
log "  Dashboard: http://$(hostname -I | awk '{print $1}'):8080"
log "  FUXA HMI:  http://$(hostname -I | awk '{print $1}'):1880"
log "  API Docs:  http://$(hostname -I | awk '{print $1}'):8080/docs"
log ""
log "  Config:    $CONFIG_DIR/config.env"
log "  Logs:      journalctl -u pifactory -f"
log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
